close all
clear all
clc

h = 0.005;
t = 0:h:10;

b = zeros(13,length(t));
b(:,1) = [0;...
          0;...
          0;...
          0;...
          0;...
          0;...
          1;...
          0;...
          0;...
          0;...
          0;...
          0;...
          0];
TF = [1000*ones(1,length(t));...
      0*ones(1,length(t));...
      0*ones(1,length(t));...
      1000*ones(1,length(t));...
      0*ones(1,length(t));...
      0*ones(1,length(t))];

for ii = 1:length(t) - 1
    k1 = neEqQuat(b(:,ii),TF(:,ii));
    k2 = neEqQuat(b(:,ii)+k1*h/2,TF(:,ii));
    k3 = neEqQuat(b(:,ii)+k2*h/2,TF(:,ii));
    k4 = neEqQuat(b(:,ii)+k3*h,TF(:,ii));
    b(:,ii+1) = b(:,ii) + h*(k1/6 + k2/3 + k3/3 +k4/6);
end

for ii = 1:length(b)

    draw_AUV(b(:,ii));
    drawnow
end